In [1]:
import torch

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [8]:
vector = torch.tensor([2,1])
vector

tensor([2, 1])

In [9]:
vector.ndim

1

In [15]:
MATRIX = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.7780, 0.2300, 0.1671, 0.0331],
         [0.1544, 0.6412, 0.8773, 0.5080],
         [0.8483, 0.5433, 0.9286, 0.6086]]),
 torch.float32)

In [18]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [26]:
MATRIX @ MATRIX

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])